# Generated by Django 5.0.7 on 2024-08-05 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_conversation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='machinemodel',
            unique_together={('model_name', 'serial_number_start', 'serial_number_end')},
        ),
    ]
